routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Controllers\Blog\PostsController;


Route::get('/', 'WelcomeController@index')->name('welcome');

Route::get('blog/posts/{post}', [PostsController::class, 'show'])->name('blog.show');

Route::get('blog/categories/{category}', [PostsController::class, 'category'])->name('blog.category');

Route::get('blog/tags/{tag}', [PostsController::class, 'tag'])->name('blog.tag');


Auth::routes();


Route::middleware(['auth'])->group(function () {

    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('categories', 'CategoriesController');

    Route::resource('posts', 'PostsController');

    Route::resource('tags', 'TagsController');

    Route::get('trashed-posts', 'PostsController@trashed')->name('trashed-posts.index');

    Route::put('restore-post/{post}', 'PostsController@restore')->name('restore-posts');

});


Route::middleware(['auth', 'admin'])->group(function () {

    Route::get('users/profile', 'UsersController@edit')->name('users.edit-profile');

    Route::put('users/profile', 'UsersController@update')->name('users.update-profile');

    Route::get('users', 'UsersController@index')->name('users.index');

    Route::post('users/{user}/make-admin', 'UsersController@makeAdmin')->name('users.make-admin');
});


//Route::get('/home', 'HomeController@index')->name('home');
//
//Route::resource('categories', 'CategoriesController');
//
////Route::resource('posts', 'PostsController')->middleware(['auth', 'verifyCategoriesCount']);
//Route::resource('posts', 'PostsController')->middleware(['auth']);
//
//Route::get('trashed-posts', 'PostsController@trashed')->name('trashed-posts.index');
//
//Route::put('restore-post/{post}', 'PostsController@restore')->name('restore-posts');

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    protected $fillable = ['name'];

    public function posts()
    {
        return $this->belongsToMany(Post::class);
    }
}

app/Http/Controllers/TagsController.php
<?php

namespace App\Http\Controllers;

use App\Tag;
use App\Http\Requests\Tags\CreateTagRequest;
use App\Http\Requests\Tags\UpdateTagRequest;

class TagsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
//        GET COLLECTIONS ***************************************************

//        dd(Tag::first()->posts()->where('published_at', now())->get());
//        dd(Tag::first()->posts()->get());

//        dd(Tag::first()->posts);

        return view('tags.index')->with('tags', Tag::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('tags.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(CreateTagRequest $request)
    {
        //
//        $this->validate($request, [
//
//            'name' => 'required|unique:tags'
//
//        ]);

//        $newTag = new Tag();

        Tag::create([

            'name' => $request->name
        ]);

        session()->flash('success', 'Tag Created Successfully');

        return redirect(route('tags.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */

    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */

    public function edit(Tag $tag)
    {
        return view('tags.create')->with('tag', $tag);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */

    public function update(UpdateTagRequest $request, Tag $tag)
    {
//        $tag->name = $request->name;
//        $tag->save();

        $tag->update([

            'name' => $request->name
        ]);

        session()->flash('success', 'Tag Updated Successfully');

        return redirect(route('tags.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */

    public function destroy(Tag $tag)
    {
        if ($tag->posts->count() > 0) {

            session()->flash('warning', 'Tag Can Not Be Deleted Because It Has Some Posts!!!');

            return redirect()->back();
        }

        $tag->delete();

        session()->flash('error', 'Tag Deleted Successfully !!!');

        return redirect(route('tags.index'));
    }
}

resources/views/tags/create.blade.php
@extends('layouts.app')

@section('content')

    <div class="card card-default">

        <h4 class="card-header font-weight-bold text-center">
            {{isset($tag)? 'Edit Tag': 'Create Tag'}}
        </h4>

        <div class="card-body">

            {{--****************************************ERROR MESSAGE****************************************--}}
            @include('partials.errors')

            {{--            @if($errors->any())--}}
            {{--                <div class="alert alert-danger">--}}
            {{--                    <ul class="list-group">--}}
            {{--                        @foreach($errors->all() as $error)--}}
            {{--                            <li class="list-group-item text-danger">--}}
            {{--                                {{$error}}--}}
            {{--                            </li>--}}
            {{--                        @endforeach--}}
            {{--                    </ul>--}}
            {{--                </div>--}}
            {{--            @endif--}}
            {{--************************************* END ERROR MESSAGE****************************************--}}

            <form action="{{isset($tag)
                                ? route('tags.update', $tag->id)
                                : route('tags.store')}}"
                  method="POST">

                @csrf

                @if(isset($tag))

                    @method('PUT')

                @endif

                <div class="form-group">
                    <label for="name">Name</label>

                    <input type="text" id="name" class="form-control" name="name"
                           value="{{isset($tag)? $tag->name: ''}}">
                </div>
                <div class="form-group">
                    <button class=" btn btn-success">
                        {{isset($tag)? 'Update Tag': 'Create Tag'}}
                    </button>
                </div>

            </form>
        </div>
    </div>

@endsection

resources/views/tags/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="d-flex justify-content-end mb-2">
        <a href="{{route('tags.create')}}" class="btn btn-success float-right">Add Tag</a>
    </div>

    <div class="card card-default">
        <h4 class="card-header text-center font-weight-bold">Tags</h4>

        <div class="card-body">

            @if($tags->count()>0)

                <table class="table table-bordered text-center">

                    <thead class="thead-light">
                    <tr>
                        <th scope="col">NAME</th>
                        <th scope="col">Post Count</th>
                        <th colspan="2">ACTIONS</th>
                    </tr>
                    </thead>

                    <tbody class="text-center">

                    @foreach($tags as $tag)
                        <tr>
                            <td>
                                {{$tag->name}}
                            </td>

                            <td>
                                {{$tag->posts->count()}}
                            </td>

                            <td>
                                <a href="{{route('tags.edit',$tag->id)}}"
                                   class="btn btn-secondary btn-sm">EDIT</a>
                            </td>

                            <td>
                                <button class="btn btn-danger btn-sm" onclick="handleDelete({{$tag->id}})">DELETE
                                </button>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>

                </table>

            @else
                <h3 class="text-center">No Tags Yet!!</h3>
        @endif


        <!-- Modal -->
            <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
                 aria-hidden="true">
                <div class="modal-dialog" role="document">

                    <form action="" method="POST" id="deleteTagForm">
                        @csrf
                        @method('DELETE')

                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="deleteModalLabel">Delete Tag</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <p class="text-center font-weight-bold">
                                    Are You Sure Delete Tag !!
                                </p>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">NO GoBack</button>
                                <button type="submit" class="btn btn-danger">YES Delete</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>

        </div>
    </div>

@endsection

@section('scripts')

    <script>
        function handleDelete(id) {
            let form = document.getElementById('deleteTagForm');
            form.action = '/tags/' + id;
            // console.log('delete call', form);
            $('#deleteModal').modal('show')
        }
    </script>

@endsection