routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Controllers\Blog\PostsController;


Route::get('/', 'WelcomeController@index')->name('welcome');

Route::get('blog/posts/{post}', [PostsController::class, 'show'])->name('blog.show');

Route::get('blog/categories/{category}', [PostsController::class, 'category'])->name('blog.category');

Route::get('blog/tags/{tag}', [PostsController::class, 'tag'])->name('blog.tag');


Auth::routes();


Route::middleware(['auth'])->group(function () {

    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('categories', 'CategoriesController');

    Route::resource('posts', 'PostsController');

    Route::resource('tags', 'TagsController');

    Route::get('trashed-posts', 'PostsController@trashed')->name('trashed-posts.index');

    Route::put('restore-post/{post}', 'PostsController@restore')->name('restore-posts');

});


Route::middleware(['auth', 'admin'])->group(function () {

    Route::get('users/profile', 'UsersController@edit')->name('users.edit-profile');

    Route::put('users/profile', 'UsersController@update')->name('users.update-profile');

    Route::get('users', 'UsersController@index')->name('users.index');

    Route::post('users/{user}/make-admin', 'UsersController@makeAdmin')->name('users.make-admin');
});


//Route::get('/home', 'HomeController@index')->name('home');
//
//Route::resource('categories', 'CategoriesController');
//
////Route::resource('posts', 'PostsController')->middleware(['auth', 'verifyCategoriesCount']);
//Route::resource('posts', 'PostsController')->middleware(['auth']);
//
//Route::get('trashed-posts', 'PostsController@trashed')->name('trashed-posts.index');
//
//Route::put('restore-post/{post}', 'PostsController@restore')->name('restore-posts');

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Storage;

class Post extends Model

{
    use SoftDeletes;

    protected $dates = [
        'published_at'
    ];

    protected $fillable = [

        'title', 'description', 'subtitle', 'image', 'published_at', 'category_id', 'user_id'
    ];

    /**
     * Delete Image From Storage
     * @return void
     */
    public function deleteImage()
    {
        Storage::delete($this->image);
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function tags()
    {
        return $this->belongsToMany(Tag::class);
    }

    /**
     * Check if post has tag
     * @param $tagId
     * @return bool
     */
    public function hasTag($tagId)
    {
        return in_array($tagId, $this->tags->pluck('id')->toArray());
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

//****************************PUBLISHED AT TIME *********************************
    public function scopePublished($query)
    {
        return $query->where('published_at', '<=', now());
    }

//******************************* SEARCH ****************************************
    public function scopeSearched($query)
    {
        $search = request()->query('search');

        if (!$search) {
            return $query->published();
        }

        return $query->published()->where('title', 'LIKE', "%{$search}%");
    }
}

app/Http/Controllers/Blog/PostsController.php
<?php

namespace App\Http\Controllers\Blog;

use App\Category;
use App\Tag;
use App\Http\Controllers\Controller;
use App\Post;
use Illuminate\Http\Request;

class PostsController extends Controller
{
    public function show(Post $post)
    {
        return view('blog.show')->with('post', $post);
    }

    public function category(Category $category)
    {
//        $search = request()->query('search');
//
//        if ($search) {
//
//            $posts = $category->posts()
//                ->where('title', 'LIKE', "%{$search}%")->simplePaginate(2);
//
//        } else {
//
//            $posts = $category->posts()->simplePaginate(4);
//        }

        return view('blog.category')
            ->with('category', $category)
            ->with('posts', $category->posts()->searched()->orderBy('updated_at','DESC')->simplePaginate(2))
//          ->with('posts', $posts)
//          ->with('posts', $category->posts()->simplePaginate(2))
            ->with('categories', Category::all())
            ->with('tags', Tag::all());
    }

    public function tag(Tag $tag)
    {
        return view('blog.tag')
            ->with('tag', $tag)
            ->with('categories', Category::all())
            ->with('tags', Tag::all())
            ->with('posts', $tag->posts()->searched()->orderBy('updated_at','DESC')->simplePaginate(4));
    }
}

app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\Posts\CreatePostRequest;
use App\Http\Requests\Posts\UpdatePostRequest;
use App\Category;
use App\Tag;
use App\Post;

class PostsController extends Controller
{

    public function __construct()
    {
        $this->middleware('verifyCategoriesCount')->only('create', 'store');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('posts.index')->with('posts', Post::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('posts.create')->with('categories', Category::all())->with('tags', Tag::all());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreatePostRequest $request)
    {
//        dd($request->all());
//*********************Upload the image to storage *******************

//        dd($request->image->store('posts'));
        $image = $request->image->store('posts');

//********************* Post Create *******************
        $post = Post::create([

            'title' => $request->title,
            'description' => $request->description,
            'subtitle' => $request->subtitle,
            'image' => $image,
            'published_at' => $request->published_at,
            'category_id' => $request->category,
            'user_id' => auth()->user()->id
        ]);

        if ($request->tags) {
            $post->tags()->attach($request->tags);
        }
//********************* Session message *******************
        session()->flash('success', 'POST Create successfully!');

//********************* Redirect *******************
        return redirect(route('posts.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
//        dd($post->tags->pluck('id')->toArray());

        return view('posts.create')->with('post', $post)->with('categories', Category::all())->with('tags', Tag::all());
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdatePostRequest $request, Post $post)
    {
        $data = $request->only('title', 'description', 'subtitle', 'published_at');

//        New IMAGE************
        if ($request->hasFile('image')) {
//            Upload Image*******************
            $image = $request->image->store('posts');

//          Delete image **************************
//          Storage::delete($post->image);

            $post->deleteImage();

            $data['image'] = $image;
        }

//**********************Tags Update Selected ***************************************
        if ($request->tags) {
            $post->tags()->sync($request->tags);
        }

//****************Update Attributes **************
        $post->update($data);

        session()->flash('success', 'Post Updated successfully ✔');

        return redirect(route('posts.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $post = Post::withTrashed()->where('id', 'LIKE', $id)->firstOrFail();

        if ($post->trashed()) {

//          Deleted Permanently Form Storage *****************
//            Storage::delete($post->image);

            $post->deleteImage();

            $post->forceDelete();

        } else {

            $post->delete();
        }
//********************* Session message *******************
        session()->flash('error', 'Post Deleted successfully 😜');

//********************* Redirect ********************************
        return redirect(route('posts.index'));
    }

    /**
     * Display all trashed of post .
     * @param int $id
     * @return \Illuminate\Http\Response
     */

    public function trashed()
    {
        $trashed = Post::onlyTrashed()->get();

        return view('posts.index')->with('posts', $trashed);
    }

    public function restore($id)
    {
        $post = Post::withTrashed()->where('id', 'LIKE', $id)->firstOrFail();

        $post->restore();

        //********************* Session message *******************
        session()->flash('success', 'Post Restore successfully 💚');

        return redirect()->back();
    }
}

resources/views/posts/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="card card-default">
        <h4 class="card-header font-weight-bold text-center">

            {{isset($post)? 'Edit Post': 'Create Post'}}

        </h4>
        <div class="card-body">
            {{--************************* Any Errors Catch Here *************************** --}}
            @include('partials.errors')

            <form
                action="{{isset($post)? route('posts.update',$post->id):  route('posts.store') }}"
                method="POST"
                enctype="multipart/form-data"
            >

                @csrf

                @if(isset($post))
                    @method('PUT')
                @endif


                <div class="form-group">
                    <label for="title">Title</label>
                    <input type="text" name="title" id="title" class="form-control"
                           value="{{isset($post)? $post->title: ""}}">

                </div>

                <div class="form-group">
                    <label for="description">Description</label>
                    <textarea name="description" id="description" class="form-control" cols="4" rows="4">
                        {{isset($post)? $post->description : ""}}
                    </textarea>
                </div>

                <div class="form-group">
                    <label for="subtitle">Content</label>
                    {{--<textarea name="subtitle" id="subtitle" class="form-control" cols="2" rows="2"></textarea>--}}

                    <input id="subtitle" type="hidden" name="subtitle" value="{{isset($post)? $post->subtitle : ""}}">
                    <trix-editor input="subtitle"></trix-editor>
                </div>

                <div class="form-group">
                    <label for="published_at">Published At</label>
                    <input type="text" name="published_at" id="published_at" class="form-control"
                           value="{{isset($post)? $post->published_at : ""}}"
                    >
                </div>
                @if(isset($post))
                    <div class="form-group ">
                        <img src="/storage/{{($post->image)}}" width="100%" class="img-thumbnail">
                    </div>
                @endif
                <div class="form-group">
                    <label for="image">Image</label>
                    <input type="file" name="image" id="image" class="form-control">
                </div>

                <div class="form-group">
                    <label for="category">Category</label>

                    <select name="category" id="category" class="form-control">
                        @foreach($categories as $category)

                            <option
                                value="{{$category->id}}"

                                @if(isset($post))
                                @if($category->id === $post->category_id)
                                selected
                                @endif
                                @endif
                            >

                                {{$category->name}}

                            </option>

                        @endforeach
                    </select>
                </div>

                @if($tags->count() > 0)
                    <div class="form-group">
                        <label for="tags">Tags</label>

                        <select name="tags[]" id="tags" class="form-control tag-selector" multiple>
                            @foreach($tags as $tag)
                                <option value="{{$tag->id}}"

                                        @if(isset($post))
                                        @if($post->hasTag($tag->id))
                                        selected
                                    @endif
                                    @endif
                                >
                                    {{$tag->name}}
                                </option>
                            @endforeach
                        </select>
                    </div>
                @endif

                <div class="form-group text-center">
                    <button type="submit" class="btn btn-success">
                        {{isset($post)? 'Update Post' : 'Create Post'}}
                    </button>
                </div>

            </form>
        </div>
    </div>
@endsection

@section('scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.1/trix.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script>

    <script>
        flatpickr('#published_at',
            {
                enableTime: true,
                enableSeconds: true
            })

        // In your Javascript (external .js resource or <script> tag)
        $(document).ready(function () {
            $('.tag-selector').select2();
        });
    </script>
@endsection

@section('css')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.1/trix.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css" rel="stylesheet"/>
@endsection

resources/views/posts/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="d-flex justify-content-end mb-2">
        <a href="{{route('posts.create')}}" class="btn btn-success float-right">Add Post</a>
    </div>

    <div class="card card-default">
        <h4 class="card-header text-center font-weight-bold">Posts</h4>

        <div class="card card-body">

            @if($posts->count()>0)

                <table class="table table-bordered text-center">

                    <thead class="thead-light">
                    <tr>
                        <th>IMAGE</th>
                        <th>TITLE</th>
                        <th>CATEGORY</th>
                        <th colspan="2">ACTIONS</th>
                    </tr>
                    </thead>

                    <tbody class="text-center">

                    @foreach($posts as $post)
                        <tr>
                            <td>
                                <img src="/storage/{{ $post->image }}" width="120px" height="80px" alt="Imag">
                            </td>

                            <td class="align-middle">
                                {{$post->title}}
                            </td>

                            <td class="align-middle">

                                <a href="{{route('categories.edit', $post->category->id)}}">
                                    {{$post->category->name}}
                                </a>

                            </td>

                            @if($post->trashed())

                                <td class="align-middle">

                                    <form action="{{route('restore-posts', $post->id)}}" method="POST">

                                        @csrf
                                        @method('PUT')

                                        <button type="submit" class="btn btn-success btn-sm">Restore</button>
                                    </form>
                                </td>

                            @else

                                <td class="align-middle">
                                    <a href="{{route('posts.edit', $post->id)}}"
                                       class="btn btn-secondary btn-sm">EDIT</a>
                                </td>

                            @endif

                            <td class="align-middle">

                                <form action="{{ route('posts.destroy', $post->id) }}" method="POST">
                                    @csrf
                                    @method('DELETE')

                                    <button type="submit" class="btn btn-danger btn-sm">
                                        {{$post->trashed() ? "Delete": "Trash"}}
                                    </button>
                                </form>
                            </td>

                        </tr>
                    @endforeach

                    </tbody>
                </table>

            @else
                <h3 class="text-center">NO POST YET !!</h3>
            @endif
        </div>
    </div>
@endsection